export let DZIALY = [
    {
        id: 1,
        imienazwisko: 'Karolina Kowalska',
        przeznaczenie: 'Internet i Telewizja ',
        opis: 'faktury za internet, telewizję, usługi głosowe oraz inne dodatkowe zwiazane z działem internet',
        przedrostekNumeruKonta: 0,
        nazwaFirmy: 'PPHU NECIK Jan Kowalski',
        ulica: 'ul. Słowianska',
        numer: '53/2',
        kodPocztowy: '00-300',
        miejscowosc: 'Warszawa',
        nip: '7884563214',
        email: 'pomoc@necik.com',
    },
    {
        id: 2,
        imienazwisko: 'Adrian Wilkołajczak',
        przeznaczenie: 'Hosting i domeny',
        opis: 'faktury za hosting, domeny, certyfikaty SSL i inne działania zwiazane z działem hosting',
        przedrostekNumeruKonta: 777,
        nazwaFirmy: 'PPHU NECIK Jan Kowalski',
        ulica: 'ul. Słowianska',
        numer: '53/2',
        kodPocztowy: '00-300',
        miejscowosc: 'Warszawa',
        nip: '7884563214',
        email: 'hosting@necik.com',
    }
];
