import { Customer } from "./customer";

export var INVOICE = {
    dzial: {
        id: 0,
        imienazwisko: "<NIE ZDEFINIOWANO>",
        przeznaczenie: "<NIE ZDEFINIOWANO>",
        opis: "<NIE ZDEFINIOWANO>",
        przedrostekNumeruKonta: 0,
        nazwaFirmy: "<NIE ZDEFINIOWANO>",
        ulica: "<NIE ZDEFINIOWANO>",
        numer: "<NIE ZDEFINIOWANO>",
        kodPocztowy: "<NIE>",
        miejscowosc: "<ZDEFINIOWANO>",
        nip: "<NIE ZDEFINIOWANO>",
        email: "<NIE ZDEFINIOWANO>",
    },
    customer: {
        id: 0,
        lastname: "<NIE ZDEFINIOWANO>",
        name: "<NIE ZDEFINIOWANO>",
        status: 0,
        zip: "<NIE ZDEFINIOWANO>",
        city: "<NIE ZDEFINIOWANO>",
        ten: "<NIE ZDEFINIOWANO>",
        ssn: "<NIE ZDEFINIOWANO>",
        regon: "<NIE ZDEFINIOWANO>",
        rbe: "<NIE ZDEFINIOWANO>",
        icn: "<NIE ZDEFINIOWANO>",
        info: "<NIE ZDEFINIOWANO>",
        notes: "<NIE ZDEFINIOWANO>",
        creationdate: 0,
        moddate: 0,
        creatorid: 0,
        modid: 0,
        deleted: 0,
        message: "<NIE ZDEFINIOWANO>",
        pin: "<NIE ZDEFINIOWANO>",
        cutoffstop: 0,
        consentdate: 0,
        type: 0,
        divisionid: 0,
        paytime: 0,
        countryid: 0,
        paytype: 0,
        einvoice: 0,
        invoicenotice: 0,
        mailingnotice: 0,
        post_zip: "<NIE ZDEFINIOWANO>",
        post_city: "<NIE ZDEFINIOWANO>",
        post_countryid: 0,
        post_name: "<NIE ZDEFINIOWANO>",
        street: "<NIE ZDEFINIOWANO>",
        building: "<NIE ZDEFINIOWANO>",
        apartment: "<NIE ZDEFINIOWANO>",
        post_street: "<NIE ZDEFINIOWANO>",
        post_building: "<NIE ZDEFINIOWANO>",
        post_apartment: "<NIE ZDEFINIOWANO>",
        extid: "<NIE ZDEFINIOWANO>",
    },
};
